package sky7.host;

public enum HOST_STATE {
    BEGIN, WAIT_FOR_PLAYERS, PLAY_NEXT_ROUND, PLAY_NEXT_PHASE, TERMINATED, BEGIN_PROCESSING, DISTRIBUTE_REGISTRY, FINISHED, WAITING_FOR_PROCESSING, DEAL_CARDS
}
